# Generated by Django 5.1 on 2024-08-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_team_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
