# Generated by Django 5.1 on 2024-08-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='avatar',
            new_name='image',
        ),
    ]
