# Generated by Django 5.1 on 2024-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_avatar_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='team')),
            ],
            options={
                'verbose_name': 'TeamBlock',
                'verbose_name_plural': 'TeamBlocks',
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
