# Generated by Django 5.1 on 2024-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teamblock_delete_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamblock',
            options={'verbose_name': 'Team Block', 'verbose_name_plural': 'Team Blocks'},
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='image',
            field=models.ImageField(upload_to='team_blocks'),
        ),
    ]
