# Generated by Django 5.1 on 2024-08-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teamblock_options_alter_teamblock_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
    ]
