# Generated by Django 5.1 on 2024-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=250)),
                ('img', models.ImageField(upload_to='courses')),
            ],
            options={
                'verbose_name': 'courses',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
