# Generated by Django 5.1 on 2024-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_courses_delete_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon-2class', max_length=50, null=True),
        ),
    ]
