# Generated by Django 5.1 on 2024-09-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_datatime_socials_courses_name_courses_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.FloatField(default=0.0, max_length=55),
        ),
    ]
