# Generated by Django 5.1 on 2024-09-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(default=0.0, max_length=55),
        ),
    ]
