# Generated by Django 5.1 on 2024-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_courses_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatime',
            old_name='html_clock',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='datatime',
            name='clock',
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_html_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
