# Generated by Django 5.1 on 2024-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_html_clock_datatime_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamblock',
            name='social_html_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
