# Generated by Django 5.1 on 2024-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_html_class_socials_socials_html_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='socials_html_class',
        ),
        migrations.AddField(
            model_name='socials',
            name='social_html_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_html_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
