# Generated by Django 5.1 on 2024-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_socials_socials_html_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='social_html_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
