# Generated by Django 4.2.13 on 2024-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_avatarsocials_delete_socials_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTime',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='img',
        ),
        migrations.AddField(
            model_name='courses',
            name='data_day',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='hours',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='icon_data',
            field=models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='icon_hours',
            field=models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='courses'),
        ),
    ]
