# Generated by Django 4.2.13 on 2024-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_datatime_remove_courses_img_courses_data_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'event',
            },
        ),
        migrations.RemoveField(
            model_name='courses',
            name='data_day',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='hours',
        ),
    ]
