# Generated by Django 4.2.13 on 2024-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_event_duration_event_duration_in_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='icon_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='icon_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_in_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
