# Generated by Django 4.2.13 on 2024-09-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_courses_icon_data_alter_courses_icon_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='courses',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration_in_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='icon_data',
            field=models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='icon_hours',
            field=models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(default=0.0, max_length=55),
        ),
    ]
