# Generated by Django 4.2.13 on 2024-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_event_courses_data_courses_duration_in_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration_in_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(max_length=55),
        ),
    ]
