# Generated by Django 4.2.13 on 2024-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_feature_tag_alter_courses_duration_in_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='StudentReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='reviews')),
                ('total_reviews', models.CharField(max_length=400)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='avatarsocials',
            options={'verbose_name': 'AvatarSocial', 'verbose_name_plural': 'AvatarSocials'},
        ),
    ]
