# Generated by Django 4.2.13 on 2024-09-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_socials_studentreviews_alter_avatarsocials_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'StudentReviews'},
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='text',
        ),
        migrations.AddField(
            model_name='footertext',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footertext',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
