# Generated by Django 4.2.13 on 2024-09-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_studentreviews_options_remove_footertext_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreviews',
            options={'verbose_name': 'StudentReview', 'verbose_name_plural': 'StudentReviews'},
        ),
    ]
