# Generated by Django 4.2.13 on 2024-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_studentreviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='text3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
