# Generated by Django 4.2.13 on 2024-09-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_footertext_text3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreviews',
            old_name='first_name',
            new_name='name',
        ),
    ]
