# Generated by Django 4.2.13 on 2024-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_contactinfo_headquarter_alter_studentreviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
