# Generated by Django 4.2.13 on 2024-09-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_contactust'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUst',
            new_name='ContactUs',
        ),
    ]
