# Generated by Django 5.1 on 2024-10-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_contactust_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarSocials',
        ),
        migrations.RenameField(
            model_name='teamblock',
            old_name='social_html_class',
            new_name='social_html_class1',
        ),
        migrations.RenameField(
            model_name='teamblock',
            old_name='social_title',
            new_name='social_title1',
        ),
        migrations.RenameField(
            model_name='teamblock',
            old_name='social_url',
            new_name='social_url1',
        ),
        migrations.RemoveField(
            model_name='studentreviews',
            name='html_class',
        ),
        migrations.RemoveField(
            model_name='studentreviews',
            name='total_reviews',
        ),
        migrations.AddField(
            model_name='studentreviews',
            name='reviews_class1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='studentreviews',
            name='reviews_class2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='studentreviews',
            name='reviews_class3',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='studentreviews',
            name='reviews_class4',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='studentreviews',
            name='reviews_class5',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_html_class2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_html_class3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_title3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_url2',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teamblock',
            name='social_url3',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
