# Generated by Django 5.1 on 2024-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_avatarsocials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Quick Links',
                'verbose_name_plural': 'Quick Links',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='studentreviews',
            options={'verbose_name': 'Student Review', 'verbose_name_plural': 'Student Reviews'},
        ),
    ]
