# Generated by Django 5.1 on 2024-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_quicklinks_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinks',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
