# Generated by Django 4.2.13 on 2024-11-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_quicklinks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicklinks',
            name='url',
        ),
    ]
